version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - '6000:5432'
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: