version: '3'
services:
  backend:
    build:
      context: ./packages/backend
    volumes:
      - /app/node_modules
      - ./packages/backend:/app
    ports:
      - '4000:4000'
    restart: always
  frontend:
    build:
      context: ./packages/frontend
    volumes:
      - /app/node_modules
      - ./packages/frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: always