version: '3'
services:
  backend:
    build:
      context: ./packages/backend
    ports:
      - '4000:4000'
    restart: always
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=logs_user
      - DATABASE_PASSWORD=complex_password123
      - DATABASE_NAME=logs_database
    depends_on:
      - db
  frontend:
    build:
      context: ./packages/frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: always
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=logs_user
      - POSTGRES_PASSWORD=complex_password123
      - POSTGRES_DB=logs_database
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: